version: "3.9"

services:
  app:
    depends_on:
      - postgres_db
    build:
      context: ./app
      dockerfile: Dockerfile

    image: flow-k8s
    environment:
      - PORT=8000
    env_file:
      - app/.env
    ports:
      - 8000:8000
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"

  postgres_db:
    image: postgres:13.3
    restart: always
    command: -p 5432
    env_file:
      - app/.env
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  # nginx:
  #   image: :nginx:1.21.1-alpine
  #   restart: always
  #   ports:
  #     - 80:80
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile

  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/static:/static
  
  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - 6379:6379
    expose:
      - "6379"
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:
