# Generated by Django 4.2.6 on 2023-11-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='uuid',
        ),
    ]
