# Generated by Django 4.2.6 on 2023-11-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_remove_task_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='subarea_department',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='task',
            name='area',
        ),
    ]
