# Generated by Django 4.2.5 on 2023-09-25 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('position', models.CharField(choices=[('GM', 'General Manager'), ('TL', 'Team Leader'), ('TC', 'Team Coordinator'), ('EX', 'Expert'), ('AG', 'Agent')], max_length=4, null=True)),
                ('team', models.CharField(choices=[('DG1', 'Digital 1'), ('DG2', 'Digital 2'), ('DG3', 'Digital 3'), ('FL', 'First Line'), ('FB', 'Flying Blue'), ('MI', 'Management Information'), ('MG', 'Management'), ('OF', 'Office'), ('SP', 'Specialist')], max_length=4, null=True)),
                ('birthday', models.DateField()),
                ('contract_start', models.DateField()),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('afr_id', models.CharField(max_length=20)),
                ('windows_account_expiry_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number_2', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contacts', models.TextField(blank=True, null=True)),
                ('blood_type', models.CharField(choices=[('B Rh+', 'B Rh+'), ('B Rh-', 'B Rh-')], max_length=10, null=True)),
                ('schengen_visa_status', models.BooleanField(default=False)),
                ('military_service_status', models.BooleanField(default=False)),
                ('safety_certificat_status', models.BooleanField(default=False)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
