# Generated by Django 4.2.6 on 2023-10-21 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_blood_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='team',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DG1', 'Digital 1'), ('DG2', 'Digital 2'), ('DG3', 'Digital 3'), ('FL', 'First Line'), ('FB', 'Flying Blue'), ('MI', 'Management Information'), ('MG', 'Management'), ('OF', 'Office'), ('SP', 'Specialist')], max_length=20)),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_coordinator', to='employee.employee')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_leader', to='employee.employee')),
                ('members', models.ManyToManyField(related_name='team_members', to='employee.employee')),
            ],
        ),
    ]
