# Generated by Django 4.2.6 on 2023-10-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_team_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='afr_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
