# Generated by Django 4.2.6 on 2023-10-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_afr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='afr_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
