# Generated by Django 4.2.6 on 2023-10-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_afr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to='employee.employee'),
        ),
    ]
