# Generated by Django 4.2.6 on 2023-10-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='current_allocation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='yearly_allocation_renawal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
