# Generated by Django 4.2.6 on 2023-10-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_current_allocation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='yearly_allocation_renawal',
            new_name='yearly_allocation',
        ),
    ]
