# Generated by Django 4.2.6 on 2023-10-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_rename_yearly_allocation_renawal_employee_yearly_allocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='current_allocation',
            new_name='alocation_balance',
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('GM', 'General Manager'), ('HR', 'Human Resources'), ('TL', 'Team Leader'), ('TC', 'Team Coordinator'), ('EX', 'Expert'), ('AG', 'Agent')], max_length=4, null=True),
        ),
    ]
