# Generated by Django 4.2.6 on 2023-10-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_rename_current_allocation_employee_alocation_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_allocation_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
