# Generated by Django 4.2.6 on 2023-10-21 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('position', models.CharField(choices=[('GM', 'General Manager'), ('HR', 'Human Resources'), ('TL', 'Team Leader'), ('TC', 'Team Coordinator'), ('EX', 'Expert'), ('AG', 'Agent')], max_length=4, null=True)),
                ('alocation_balance', models.IntegerField(blank=True, null=True)),
                ('yearly_allocation', models.IntegerField(blank=True, null=True)),
                ('last_allocation_update', models.DateField(blank=True, null=True)),
                ('birthday', models.DateField()),
                ('contract_start', models.DateField()),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('afr_id', models.CharField(blank=True, max_length=20, null=True)),
                ('windows_account_expiry_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number_2', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contacts', models.TextField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, choices=[('A Rh+', 'A Rh+'), ('A Rh-', 'A Rh-'), ('B Rh+', 'B Rh+'), ('B Rh-', 'B Rh-'), ('AB Rh+', 'AB Rh+'), ('AB Rh-', 'AB Rh-'), ('O Rh+', 'O Rh+'), ('O Rh-', 'O Rh-')], max_length=10, null=True)),
                ('schengen_visa_status', models.BooleanField(default=False)),
                ('military_service_status', models.BooleanField(default=False)),
                ('safety_certificat_status', models.BooleanField(default=False)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DG1', 'Digital 1'), ('DG2', 'Digital 2'), ('DG3', 'Digital 3'), ('FL', 'First Line'), ('FB', 'Flying Blue'), ('MI', 'Management Information'), ('MG', 'Management'), ('OF', 'Office'), ('SP', 'Specialist')], max_length=20)),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_coordinator', to='business.employee')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_leader', to='business.employee')),
                ('members', models.ManyToManyField(to='business.employee')),
            ],
        ),
    ]
