# Generated by Django 4.2.6 on 2023-10-21 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_of', to='business.employee'),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_of', to='business.employee'),
        ),
    ]
