# Generated by Django 4.2.6 on 2023-10-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_employee_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
