# Generated by Django 4.2.6 on 2023-10-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_customer_uuid_employee_uuid_team_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
