# Generated by Django 4.2.6 on 2023-11-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_alter_employee_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='team',
            name='uuid',
        ),
    ]
