# Generated by Django 4.2.6 on 2023-11-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_remove_customer_uuid_remove_employee_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='afr_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='military_service_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_number_2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='safety_certificat_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='schengen_visa_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='windows_account_expiry_date',
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
