# Generated by Django 4.2.6 on 2023-11-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_remove_employee_address_remove_employee_afr_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
