# Generated by Django 4.2.6 on 2023-10-21 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('working from office', 'Working from Office'), ('remote working', 'Remote Working'), ('holiday', 'Holiday'), ('sick leave without report', 'Sick leave without report'), ('sick leave with report', 'Sick leave with report'), ('marriage', 'Marriage'), ('childbirth of wife', 'Childbirth of wife'), ('funeral 1st degree', 'Funeral 1st degree')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(choices=[('half day', 'Half Day'), ('full day', 'Full Day')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to='business.employee')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requestor', to='business.employee')),
            ],
        ),
    ]
