# Generated by Django 4.2.5 on 2023-09-26 12:06

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='duration',
            field=models.CharField(choices=[('half day', 'Half Day'), ('full day', 'Full Day')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default=datetime.datetime(2023, 9, 26, 12, 6, 47, 442275, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
