# Generated by Django 4.2.6 on 2023-10-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='assigned_to',
            new_name='reviewed_by',
        ),
    ]
