# Generated by Django 4.2.6 on 2023-10-21 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('request', '0002_rename_assigned_to_request_reviewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to='business.employee'),
        ),
    ]
