# Generated by Django 4.2.5 on 2023-10-15 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_blood_type'),
        ('request', '0002_request_duration_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requestor', to='employee.employee'),
        ),
    ]
