# Generated by Django 4.2.5 on 2023-10-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_request_assigned_to_alter_request_requested_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
