# Generated by Django 4.2.6 on 2023-11-08 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_rename_duration_request_duration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requested_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
